/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labmongodb;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mongodb.ErrorCategory;
import com.mongodb.MongoWriteException;
import com.mongodb.client.MongoCollection;

import org.bson.Document;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.MongoCursor;
import com.mongodb.util.JSON;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.json.*;
import org.json.*;
import java.io.FileReader; 
import java.util.Iterator; 
import java.util.Map; 
  
import org.json.simple.JSONArray; 
import org.json.simple.JSONObject; 
import org.json.simple.parser.*; 



/**
 *
 * @author joseo
 */
public class FormLabMongoDB extends javax.swing.JFrame {

    /**
     * Creates new form FormLabMongoDB
     */
    public MongoCollection collection;
    public MongoClient mongoClient;
    public MongoDatabase database;
    public FormLabMongoDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        lblSeleccione = new javax.swing.JLabel();
        btnAgregarPeli = new javax.swing.JButton();
        lblNombrePeli = new javax.swing.JLabel();
        lblGeneroPeli = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblFranquicia = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblCompania = new javax.swing.JLabel();
        lblActores = new javax.swing.JLabel();
        txtFieldNombrePeli = new javax.swing.JTextField();
        txtFieldGeneroPeli = new javax.swing.JTextField();
        txtFieldDirector = new javax.swing.JTextField();
        txtFieldFranquicia = new javax.swing.JTextField();
        txtFieldPais = new javax.swing.JTextField();
        txtFieldAno = new javax.swing.JTextField();
        txtFieldDuracion = new javax.swing.JTextField();
        txtFieldCompania = new javax.swing.JTextField();
        txtFieldActores = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtENombre = new javax.swing.JTextField();
        txtEgenero = new javax.swing.JTextField();
        txtEdirector = new javax.swing.JTextField();
        txtEfranquicia = new javax.swing.JTextField();
        txtEpais = new javax.swing.JTextField();
        txtEano = new javax.swing.JTextField();
        txtEduracion = new javax.swing.JTextField();
        txtEcompania = new javax.swing.JTextField();
        txtEactores = new javax.swing.JTextField();
        btnEditarSelected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbltitulo.setText("Regitro de Peliculas");

        lblSeleccione.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSeleccione.setText("Registrar Peliculas");

        btnAgregarPeli.setText("Agregar Pelicula");
        btnAgregarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliActionPerformed(evt);
            }
        });

        lblNombrePeli.setText("Nombre: ");

        lblGeneroPeli.setText("Género: ");

        lblDirector.setText("Director: ");

        lblFranquicia.setText("Franquicia");

        lblPais.setText("País: ");

        lblAno.setText("Año: ");

        lblDuracion.setText("Duración: ");

        lblCompania.setText("Compañia: ");

        lblActores.setText("Actores: ");

        txtFieldNombrePeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNombrePeliActionPerformed(evt);
            }
        });

        txtFieldActores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActoresActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar Peliculas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Género", "Director", "Franquicia", "País", "Año", "Duración", "Compañia", "Actores"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Editar Películas");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Género.");

        jLabel4.setText("Director: ");

        jLabel5.setText("Franquicia: ");

        jLabel6.setText("País: ");

        jLabel7.setText("Año: ");

        jLabel8.setText("Duración: ");

        jLabel9.setText("Compañia: ");

        jLabel10.setText("Actores: ");

        txtENombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtENombreActionPerformed(evt);
            }
        });

        txtEano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEanoActionPerformed(evt);
            }
        });

        btnEditarSelected.setText("Editar");
        btnEditarSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblActores)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFieldActores))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblCompania)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFieldCompania))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblDuracion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFieldDuracion))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblNombrePeli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFieldNombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGeneroPeli)
                                            .addComponent(lblDirector))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                            .addComponent(txtFieldGeneroPeli)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFranquicia)
                                            .addComponent(lblPais)
                                            .addComponent(lblAno))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldFranquicia)
                                            .addComponent(txtFieldPais)
                                            .addComponent(txtFieldAno))))
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarPeli)
                                .addGap(46, 46, 46)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarSelected)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblSeleccione)
                        .addGap(345, 345, 345)
                        .addComponent(lbltitulo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtENombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEgenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdirector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEfranquicia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEpais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEano, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEcompania, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEactores, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblSeleccione)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombrePeli)
                            .addComponent(txtFieldNombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGeneroPeli)
                            .addComponent(txtFieldGeneroPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDirector)
                            .addComponent(txtFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFranquicia)
                            .addComponent(txtFieldFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPais)
                            .addComponent(txtFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAno)
                            .addComponent(txtFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDuracion)
                            .addComponent(txtFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompania)
                            .addComponent(txtFieldCompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblActores)
                            .addComponent(txtFieldActores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarPeli)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(btnEditarSelected))
                .addGap(7, 7, 7))
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitulo)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEdirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEfranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEcompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEactores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(22, 22, 22))
        );

        jButton1.getAccessibleContext().setAccessibleName("Buscarbtn");
        jButton3.getAccessibleContext().setAccessibleName("btnEliminar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliActionPerformed
   //Get values of the movies
   String Nombre = txtFieldNombrePeli.getText();
   String Genero = txtFieldGeneroPeli.getText();
   String Director = txtFieldDirector.getText();
   String Franquicia = txtFieldFranquicia.getText();
   String Pais = txtFieldPais.getText();
   String Ano = txtFieldAno.getText();
   String Duracion = txtFieldDuracion.getText();
   String Compania = txtFieldCompania.getText();
   String Actores = txtFieldActores.getText();
   // Connect to MongoDB Server on localhost, port 27017 (default)
   mongoClient = new MongoClient(new MongoClientURI("mongodb://localhost:27017"));
   // Connect to Database "test"
   database = mongoClient.getDatabase("test");
   System.out.println("Successful database connection established. \n");

   //Insert a document into the "TestMovies" collection.
   collection = database.getCollection("TestMovies");
   Document Movie1 = new Document();
   Movie1.append("Nombre", Nombre)
         .append("Genero", Genero)
         .append("Director", Director)
         .append("Franquicia", Franquicia)
         .append("Pais", Pais)
         .append("Ano", Ano)
         .append("Duracion", Duracion)
         .append("Compania", Compania)
         .append("Actores", Actores);

    try {
       collection.insertOne(Movie1);
       System.out.println("Successfully inserted documents. \n");
    } catch (MongoWriteException mwe) {
        if (mwe.getError().getCategory().equals(ErrorCategory.DUPLICATE_KEY)) {
            System.out.println("Document with that id already exists");
        }
    }
    
    
    
       
    }//GEN-LAST:event_btnAgregarPeliActionPerformed

    private void txtFieldNombrePeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNombrePeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNombrePeliActionPerformed

    private void txtFieldActoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldActoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           DefaultTableModel Model = (DefaultTableModel) jTable2.getModel();
           //Clear Jtable2 
           while(Model.getRowCount() > 0){
               for(int i =0; i<Model.getRowCount(); i++){
                   Model.removeRow(i);
               }
           }
           // Connect to MongoDB Server on localhost, port 27017 (default)
           mongoClient = new MongoClient(new MongoClientURI("mongodb://localhost:27017"));
           // Connect to Database "test"
           database = mongoClient.getDatabase("test");
           //System.out.println("Successful database connection established. \n");   
           collection = database.getCollection("TestMovies");
           String nombrexo;
           String generoxo;
           String directorxo;
           String franquiciaxo;
           String paisxo;
           String anoxo;
           String duracionxo;
           String companiaxo;
           String actoresxo;
           String idxo;
           
            //Find and print ALL documents in the collection
            //System.out.println("Printing all the documents.");
            MongoCursor cursor = collection.find().iterator();
             while (cursor.hasNext()) {
                  Document thirdxx = (Document) cursor.next();
                  String objectx = thirdxx.toJson();
                  //System.out.println(objectx);
                  JsonObject jsonObject = new JsonParser().parse(objectx).getAsJsonObject();
                  nombrexo = jsonObject.get("Nombre").getAsString();
                  generoxo = jsonObject.get("Genero").getAsString();
                  directorxo = jsonObject.get("Director").getAsString();
                  franquiciaxo = jsonObject.get("Franquicia").getAsString();
                  paisxo = jsonObject.get("Pais").getAsString();
                  anoxo = jsonObject.get("Ano").getAsString();
                  duracionxo = jsonObject.get("Duracion").getAsString();
                  companiaxo = jsonObject.get("Compania").getAsString();
                  actoresxo = jsonObject.get("Actores").getAsString();
                  //idxo = jsonObject.get("$oid").getAsString();
                  //System.out.println(idxo);
                  
                  Model.addRow(new Object[]{nombrexo,generoxo,directorxo,franquiciaxo,paisxo,anoxo,duracionxo,companiaxo,actoresxo});
             }
          
                          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            //Get values of the movies
            String Nombrexy = txtENombre.getText();
            String Generoxy = txtEgenero.getText();
            String Directorxy = txtEdirector.getText();
            String Franquiciaxy = txtEfranquicia.getText();
            String Paisxy = txtEpais.getText();
            String Anoxy = txtEano.getText();
            String Duracionxy = txtEduracion.getText();
            String Companiaxy = txtEcompania.getText();
            String Actoresxy = txtEactores.getText();
            // Update a document
            //Get the selected row
            int rowx = jTable2.getSelectedRow();
            String Nombrexx = (jTable2.getModel().getValueAt(rowx, 0).toString());
            // Connect to MongoDB Server on localhost, port 27017 (default)
           mongoClient = new MongoClient(new MongoClientURI("mongodb://localhost:27017"));
           // Connect to Database "test"
           database = mongoClient.getDatabase("test");
           System.out.println("Successful database connection established. \n");   
           collection = database.getCollection("TestMovies");
           Document third = (Document) collection.find(Filters.eq("Nombre", Nombrexx)).first();
           //System.out.println(third.toJson());

            collection.updateOne(new Document("Nombre", Nombrexx),
                    new Document("$set", new Document("Genero", Generoxy)
                            .append("Ano", Anoxy).append("Director", Directorxy).append("Franquicia", Franquiciaxy).append("Pais", Paisxy).append("Ano", Anoxy).append("Duracion",Duracionxy).append("Compania", Companiaxy).append("Actores", Actoresxy).append("Nombre", Nombrexy))
            );

            System.out.println("\nDocuments Updated");
           

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Get the selected row
        int rowxy = jTable2.getSelectedRow();
        String Nombrexxy = (jTable2.getModel().getValueAt(rowxy, 0).toString());
        //Delete data
        // Connect to MongoDB Server on localhost, port 27017 (default)
        mongoClient = new MongoClient(new MongoClientURI("mongodb://localhost:27017"));
        // Connect to Database "test"
        database = mongoClient.getDatabase("test");
        System.out.println("Successful database connection established. \n");   
        collection = database.getCollection("TestMovies");
        System.out.println("\nDocuments deleted.");
        collection.deleteMany(Filters.eq("Nombre", Nombrexxy));

            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtENombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtENombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtENombreActionPerformed

    private void btnEditarSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSelectedActionPerformed
        //Get the selected row
        int row = jTable2.getSelectedRow();
        String Nombrex = (jTable2.getModel().getValueAt(row, 0).toString());
        String Generox = (jTable2.getModel().getValueAt(row, 1).toString());
        String Directorx = (jTable2.getModel().getValueAt(row, 2).toString());
        String Franquiciax = (jTable2.getModel().getValueAt(row, 3).toString());
        String Paisx = (jTable2.getModel().getValueAt(row, 4).toString());
        String Anox = (jTable2.getModel().getValueAt(row, 5).toString());
        String Duracionx = (jTable2.getModel().getValueAt(row, 6).toString());
        String Companiax = (jTable2.getModel().getValueAt(row, 7).toString());
        String Actoresx = (jTable2.getModel().getValueAt(row, 8).toString());
        //System.out.println(click_jtable2);
        txtENombre.setText(Nombrex);
        txtEgenero.setText(Generox);
        txtEdirector.setText(Directorx);
        txtEfranquicia.setText(Franquiciax);
        txtEpais.setText(Paisx);
        txtEano.setText(Anox);
        txtEduracion.setText(Duracionx);
        txtEcompania.setText(Companiax);
        txtEactores.setText(Actoresx);
    }//GEN-LAST:event_btnEditarSelectedActionPerformed

    private void txtEanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLabMongoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLabMongoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLabMongoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLabMongoDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLabMongoDB().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPeli;
    private javax.swing.JButton btnEditarSelected;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblActores;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCompania;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFranquicia;
    private javax.swing.JLabel lblGeneroPeli;
    private javax.swing.JLabel lblNombrePeli;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblSeleccione;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtENombre;
    private javax.swing.JTextField txtEactores;
    private javax.swing.JTextField txtEano;
    private javax.swing.JTextField txtEcompania;
    private javax.swing.JTextField txtEdirector;
    private javax.swing.JTextField txtEduracion;
    private javax.swing.JTextField txtEfranquicia;
    private javax.swing.JTextField txtEgenero;
    private javax.swing.JTextField txtEpais;
    private javax.swing.JTextField txtFieldActores;
    private javax.swing.JTextField txtFieldAno;
    private javax.swing.JTextField txtFieldCompania;
    private javax.swing.JTextField txtFieldDirector;
    private javax.swing.JTextField txtFieldDuracion;
    private javax.swing.JTextField txtFieldFranquicia;
    private javax.swing.JTextField txtFieldGeneroPeli;
    private javax.swing.JTextField txtFieldNombrePeli;
    private javax.swing.JTextField txtFieldPais;
    // End of variables declaration//GEN-END:variables
}
